apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- nextcloud-postgres-sealed-secrets.yml
- nextcloud-postgres.yaml
- origin-ca-service-key.yaml
- origin-issuer.yaml
- certificate.yaml
- ingressroute_tls.yaml

namespace: nextcloud