apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: nextcloud-pgsql
  namespace: nextcloud
spec:
  replicas: 3
  image: postgres:14.1
  database:
    size: 1Gi
    storageClassName: synology-nas-synology-csi-delete
  env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: nextcloud-postgres
          key: superUserPassword
    - name: POSTGRES_REPLICATION_PASSWORD
      valueFrom:
        secretKeyRef:
          name: nextcloud-postgres
          key: replicationUserPassword
