apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-elizondo-cloud
spec:
  secretName: bitwarden-elizondo-cloud
  dnsNames:
    - bitwardem.elizondo.cloud
  duration: 168h0m0s
  renewBefore: 24h0m0s
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: prod-issuer