apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
- service.yaml
- certificate.yaml
- ingressroute_tls.yaml
- origin-ca-service-key.yaml
- origin-issuer.yaml

namespace: bitwarden