apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-3rdparty
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: infrastructure/nextcloud-3rdparty
    repoURL: https://github.com/ElioLopez/gitops-cluster.git
    targetRevision: HEAD
  destination:
    namespace: nextcloud
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true