apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photoview-3rdparty
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: production/photoview-3rdparty
    repoURL: https://github.com/ElioLopez/gitops-cluster.git
    targetRevision: HEAD
  destination:
    namespace: photoview
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true