apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: monitoring
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    chart: prometheus-operator
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://kubernetes-charts.storage.googleapis.com/
    targetRevision: 8.12.3
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
