apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-elizondo-local
spec:
  secretName: traefik-elizondo-local
  issuerRef:
    name: k3s-ca-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - traefik.elizondo.local