apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ingressroute.yaml
- certificate.yaml

helmCharts:
- name: traefik
  repo: https://helm.traefik.io/traefik
  version: 22.0.0
  releaseName: traefik
  namespace: kube-system
  valuesInline:
    dashboard:
      enabled: true
      matchRule: Host(`traefik.elizondo.local`) || PathPrefix(`/dashboard`) || PathPrefix(`/api`)
      entryPoints: ["traefik", "web", "websecure"]
      tls: traefik-elizondo-local
    ports:
      traefik:
        expose: true
    logs:
      access:
        enabled: true
    kubernetes:
      ingressEndpoint:
        useDefaultPublishedService: true
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
  valuesMerge: merge

namespace: kube-system