apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-elizondo-local
spec:
  secretName: argocd-elizondo-local
  issuerRef:
    name: k3s-ca-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
  - argocd.elizondo.local