apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.16/manifests/install.yaml
- certificate.yaml
- ingressroute-http.yaml
- ingressroute-https.yaml
- redirect-middleware.yaml

patchesStrategicMerge:
- argocd-cmd-params-cm-patch.yml

namespace: argocd
