{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "synology-csi",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "synology-csi",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "client-info.yaml": "AgAi8h34NfVdLg5apmI5DIPHT+hljwVpDbCm4PDWndu5QaT/zl/nzZ8NkTZVLF0RF3JL/DSORYvI2mrXWwV1LdOzg9rPI/Dv2u45jBvti/tcWirZRZAJryzAUbTqrIyxOX7Yk2/k/4q/hNg5AOr1olHCh1aRiO4+8r0xxyw8vtxLZkkdt7VQ6UvLYPHT5lyS2ps4Xr4Ua6rZ/IAMdXmULzHI+53EV3O9yJSbebAHdN+9ShTc4PM8dlTzHnXstfqb4YW+oGf8u7ZgVB9zWEJJKxhQ7/oFUm2uS/8l1LtcyabgiKK4Ix3z9Ii3NdIGbAYy+DRSCs1bJ56X2iks8JzyyfAMg77TBfe9O1I8WQk0U+839WrUnbgdYfaC8Mu51PSRfZV3zsu+5HxgLU/2vKX+7Uzo2X0fXptAyc3SLuNaFqEO9Y04LRxfBrH+Ra8o5R7aCZbvee2ANn1b5q2QLym6t7btjLMJjJk9qGMleZS4CvWysYsJAHq+bG/DylLTU44uL88vW6QbcAc52x9V4ln0I5/fKSei9ExMP+Gb3edCBb4+rpBqehGZKeh6V7q5P40UGdGXbmFOdFx1qdUYmVoZOwDp5wFUafXtVB/UFTnm2yjA4HQKPo6th8kY8B5Ht5BGV+GVsa+02pfmG+HBvsYdcnnVxdrFvaswGgv08uG/6hHlaMpM/yUtMV94gu9ZEp96GlvRvtbW3aO4Nh2coGhQzXbx/rXUKx9LmzOJYjQ6oHPqbfbmpNQF9hPXxWdUakg3rcGOWXRXofmwUWkqrpOWmgLfwJaygF2XcRJ9RWoEkjFzMVODmBoKLaD/OLp1PcLYz6aADg=="
    }
  }
}
