{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "synology-csi",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "synology-csi",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "k8s_pass": "AgBeZrGWxll1fc7/8vMslwgz70w+38hfnFrG0XjWnfzXf2jWyqX/sWXPNeik4hssUlaqFqW+2SBu6pKcAc5cCAQYas8IQ1cnsXFsaSIFykNeMMPvCKqi8otBV1dZ0xmSL8Qg0absKuPMuEYnsl5Sh07PJlfkmws7BBe3ihZgzJurZ47XEzmK/1KYwqGKraXflC2K/tZ5460dN0L2/NkGz77JGaQcOI8H9+XP/DoheGzo4QCBwvGUUZvYZz792cxuHt2K5eImr9W6kro2vvorOi2vsWjLIyoQm98g09wO8g8eSGEZ8AMV5uDY23Lf17yJzMwTb4DZpIy+tCEUc+0xjSFZ65Ymmns8no6zKg0y5SqKCKqu4uo6jxcDs66JzZlBZfI1sSIFh3dHNVfQFyhiN9O+CGkqzpbVEaN/U4BqfDt3rC+5LIWPzKLRHtIUjX0vTXdZ4ie4Xah+sDtg8r2/cmRJsxtrvD7FdgtPHklV04MxmFx4mKFP4qbgsLH3nqCseQeqJGY4qhu7/AuM2ERJo5Kl5tQ1qE8F/1YFMUTjzibMnPrjoDfPJjaO3pkuKm3mKj7FK4U9JKNf5GaurX2H9bOKoZDJ6VjbfqeF1w5/qISztSJJyD5ic2VrWBMmtsr8zzPj8jD/+fn3K57xmrr+5+3/VUKmv/vyExKcYoxp+7rU+zw1tfcpfsGy3A/q83l+1qXfIA/MPNR4LtqnIBZW76MbR9+nKysAneZuCzDDsfDx/UQjUdlrl3M=",
      "k8s_user": "AgAYhd8IfsWi9Rtzo+83bFgdCDqUfq701b4EwsUqB1PqrvIHaPxMUin70oy4Pu2zSENWazwzYCMukJsoCnuO0VhyCY5fQ7qru7QxqKPhh3shbZnJxPBSEp3e/McKnKlY58uQb9R7qNR6NNhfR6zLOtKvbTScgLN2WyoYVIP7rvZe6AcLm4DPoA1xuZJ64vINAs0yF6qck7LC6PN6MxEyuHR0k/sXMioxIkKkLfU3cQALoWdciTWfnLi+mhprZMbpVQQJE9KP1X28j9rMwyEdle0ahxaTjnCzWc9E/6pUfHI7itvHNwpjDJy9mT/4nH780Ie86OOPYDilGNrw0/ynL4792L3AiZQDx6Bh+lwi9mfs5ouTYGQT9G2IqICvMYQvEXx7eeDXbiF8G5XfO/nclNLEtXawCbytuBwuskZcYLjyvvTplZ3hHBtb6pI06xf1X6D5eV2A7cNP1WhoLeQcnQsgL3Hqy/FyZSIMcgqZaIq7eI5dcmt2jWfJB/VLw+Tidx051fnlG2AITBoCTxhcQDb8qv4Z8zBAXtr6J4YCXaej6On2D7pWDEoFFP2hRl805SvJwK5hN40Unc0hy1aDpkXlTDhuMVLld4f8MZDAqeO9BCh9sT+ZNTIVDfPjvU8zltUJ3XdDACJILvU4TeQ7mBdkKooBBk8AcvWjNwfjFBWAYYiUruTGRZyYQkSof54+3A2yxdnni5l4"
    }
  }
}
