{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "synology-csi",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "synology-csi",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "client-info.yaml": "AgBgYmhDnoz7WrOBqA6lpRWoyQfRuByNpIQ3ZgEpyiRsiRl1xuQvmVfivmoO3XELKcgESIGi5RwRnWqVy1ocZAUixSdZNejfrbar4XhPVlqZ/SEhOWOAzjPuyqwbuc2t+AFEzM8P9klB9wwfOgdlGxfEzjOZ4txrFkchaTJ2S2Hzm1pSkfqVyJ8ruPMBlfGMS0as+zreqvG/rUDPaLOjjmBLD4I4Zfnm5YI0Wla7+7I+HMvcLy3hD0Y6oDTlpx5OKL9e9A03oJwXM06n2VNynx1vYjeriaE6YbtCrY2JdJq7F655FO6c1sPmEzKRH9ORlyFOJtz/62U2nERb9qejml92poyWIFM/uf1mnpoNEydxLEf+XjK1CM6CKoaQ/DWZS/wDr+jQp+U4IpWtkKkMa04csTZAVfmNTIgnFNXbzPp9ye341/BOeSItICtoO534d8GonKriOqSfoNlEjvS6FHb7WYuYo3Yk94enA0cC3i02D+CyAXUZe5vy+m8KU+1Ry5VhO9uUczBifpiB5JGdskn9sgAdF4qIuxThdZsuHKobycmSUSHvFn0BobJ8c/GFNhaqGnOSMYAL/m35hpwMkFUrt0ownnKhL0h3soC978s9ijuNtG3ZTBg8n7IHUvJCiKTMO5Y6AqlevpAEPepbmGyQx8UP9a9w2CpCCQZxvxZ8xg4UdO2Z2bHyd8nMCMC6fVO2NqqDfi4//lOvg3jUXsBeTXIjlvbKRAmjnB7QTnqLZXG51H2uoyF/sxm9ccDUnxFPLbWSPpuvr2vIfIMTezB2aCTxrAvEpV0d3pcTxRd5Yq/FviHBQawDJDFdblxcBW01o2B+cDohxBVKU1fJ8gOxy+Tn1AsXh9yvPopfOXoH0sGi"
    }
  }
}
