apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: origin-cert
spec:
  secretName: origin-cert
  dnsNames:
    - whoami.elizondo.cloud
  duration: 168h
  renewBefore: 24h
  issuerRef:
    group: cert-manager.k8s.cloudflare.com
    kind: OriginIssuer
    name: prod-issuer