apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgres-sealed-secrets.yaml
- origin-ca-service-key.yaml
- origin-issuer.yaml
- certificate.yaml
- ingressroute_tls.yaml
- postgres_cm_init.yaml
#- postgres_db.yaml

namespace: photoview