apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-ddns-unproxied
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    path: infrastructure/cloudflare-ddns-unproxied
    repoURL: https://github.com/ElioLopez/gitops-cluster.git
    targetRevision: HEAD
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=false