apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology-csi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    path: infrastructure/synology-csi
    repoURL: https://github.com/ElioLopez/gitops-cluster.git
    targetRevision: HEAD
    plugin:
      name: kustomize-build-with-helm    
  destination:
    namespace: synology-csi
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false      
    syncOptions:
    - CreateNamespace=true
    - Validate=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ApplyOutOfSync=true    
