apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synology-csi
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    path: infrastructure/synology-csi
    repoURL: https://github.com/ElioLopez/gitops-cluster.git
    targetRevision: HEAD
  destination:
    namespace: synology-csi
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
  plugin:
    name: kustomize-build-with-helm    