apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- sealed-secrets.yaml

helmCharts:
- name: synology-csi
  repo: https://ElioLopez.github.io/helm-charts
  version: 0.3.3
  releaseName: gitops-cert-manager
  namespace: synology-csi
  valuesInline:
    clientInfoSecretName: "synology-csi"
    storageClasses:
      delete:
        reclaimPolicy: Delete
        isDefault: true
      retain:
        reclaimPolicy: Retain
    volumeSnapshotClasses:
      delete:
        isDefault: true
      retain:
        deletionPolicy: Retain
  valuesMerge: merge

namespace: synology-csi

