{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "synology-csi",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "synology-csi",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "client-info.yaml": "AgBLJeWWPnfucDW0lIeTSS+Dc88SdhSjT9rSQqa8SA3et8mnqBV2ZV78+tDUW6Dp1/hXd4m9vIhhGAo9Xv1m5eK+8I+h3zTfa3ENDO9ar9rm+E1pEj1ZICobdkWK41DL2ob3A8h9JqyqOUwdOGC1nh0tc/3aULOSXHyyKObFIVouvneoX1vx8MQ0MIC1xADMGp5U/t22/2zw3x+az8mUnHD3I0+UHx1SbIbetYQ+hxOI59Qp3nqzyKtuWvgGRJcrXIdK8fnI/9Uv2aZ/4HmLLBEQM0LtHRZ/C5TTmWHIBd94DRSwuyp/wNUsXwKkQ9NFCs3eb7cqMV+WVXGgmx81ojSDXCWE+Ugfza4gm8nahl1Ndu2iemEOSgiZVbZqLoIFBx0GYbUwGbpIRYy8X2FFN4u4FLIh83KSgbg2sf3UOjlp5ob7tRSUc4dANkDAtQ6bo3Rgg6H7yAU6m5zxzFWUJCGx3PWGYGXr5q49vIF0nDRCKmrRJ7UxASQnujiE041/PI3+VIlEBlymZtemcBQr+6/48JWX5Sm+Zyiy//NVmseCqltpg1k67ZCvM2/PLVooeBXJCUQl2C98lST3uz7sPp7aFvH/kg2HskGDetVwWPn2OqG9cj7AOp019XVlUSABIyMtxf5FDAmOY1ggZ1hFaT0RXfqgyFkMC8N6weEDEo5/v0zivQHahFVQjSlmfK1e62+seQwkySz4kJnzDPpCtROQerQy6KQ5dXhBY4IE9fP1s8sWGpLhbgk4GuZXfdqvhUt7ykuIeq41swVurFAdUGvft7M7oTjrxPCqmd74gmyOyAHGLdvIVLy4MqduBUf9kYtFsBjMnQsvVRF0YtZoYQ191aYPzPA7fXJWtN57UHVEsedE"
    }
  }
}
