{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "synology-csi",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "synology-csi",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "client-info.yaml": "AgCiTAGmV+kMoaFdWMay8dqKld/6lyug+xZVeOtEhC9DDWMxawhePmCbq0uq370o1MyiCCyT9bv7h2oUcX+FQm4fDaSf3tsDsRlIOKk3s0cR10ViGL29bkFE9XgBjn2Ox7R1pNaNSGxPXX4+TFodATY1wAFOAJ8ORmDL6Pd1TmjtKTAlcR6Vki1OP1WX54+JlLuWw2FZ8lWgjb2xAC8ATF0TjhrgBz3gMBfh8Ls5COvQ2DrKidEf0+HI72c7BNyn1yp1EFU9F+9BfAsk8/AsRvdeDZzII0G3msDIbJXq2vNpkFJE5RaSgB8IUODzvoD2AQxDuFB4ihK4+WOG7F3saD3CKIgUGEg514BUZYE5zVXEi7c3o4/0NkF27+BQQ2hYYafrIiYZplM0ZCM99/Wl/VPIl0hp9QR4EFsvpeq0FiCD/RjmM1ZI6uyYEk4Ya4KT/BvnpL82cF8oDMjX6iLM8J/nCycrPMnDWdSD8J/+cToieIcI8Ca92hiO892ptBWm4ZQ/9+EFGay9+dJFUfDI3WFNkwDCAnBu0IzCIwyteQq6mcN2k36oGnO8HaA1fLJSMw7aI4n6sLe5gFUyyITZJ6T5iF2mylTl8Dj5r+50lkwnS5CLTMFSvdRg+EtmTZvNYSrxM/QzFtW+N0GRUDGpf3Z/31p/ZdfaT7Em3LC81II5HR1qAtmcaVM9lujMxTGf5WWpNNhc+soYtaEbMhaft08GN4k8I5xQrrLPbgcgfKZthagJu9Li/JadzoWtNHeoPiePLmDu1JO+9Z+g5UFyIFi1LihNHXx8QuhCNXSFh0yPqofhwrEiLURpMNK/ZkZdGlr3rjHQUbZABbP54dFA5Lcw6A2YMMBIyJ4VPt48rA4ulFI="
    }
  }
}
