{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "synology-csi",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "synology-csi",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "client-info.yaml": "AgCWrLK7JBSYKLLhMHyonGMnIeaAuBQ9CL5NiO+0Fq8H1OsIlPIlS8B6TjMVdNQ01UQWKexqzmT0IdXGU6cRv/9cDSNfdCuibWrsdgBWF4pgf4USm7hwyYAQMY6m3Id8+d0DJcV+pJfKLaKhd/lvxbfdriUC71yS76rzfReWyc8lHtYRHCOw6zQOF1Uv2N9M+lylt30DN7XsbntZj/0VB641jLN/D8kcb0fw4dWRV3RgtQaSWKqJlu/ar8eCX7Us1afjEWcOaXU5lP2MyIiC/xv8roTryBKTXRHUDFR5p/Wny24CRSpmA18mePolJ4wA+Gn3TgDlgALHJ0x3+BGi/ZirQ66g+xmBftR3+LMT6TKParlcZKA3E3MUPVFSKt4YMJxQ4OdiEvApJTA4fPgkWPlLcnWyDblq3iEPNO9xVBgUycHgEkQy+1BibDuGOc/sf7Bq05ahTsirg2CqiHy1YACsj+aTR8uU3/1wDIuVLpTzktZ232ksGRDDwvD4tbwiatp5e6QpbsksvXqDE5nj31iP8SzZoROml1FdduvMHL+gDexGE0QlcS4479MhX9vTLTbsCDyJJVOC3pFcXpt0g2rU4tF3wtfsoZ0/FUvy6nAadX5CqZHnWhQa0e23O/oriJyAetGIeXqhvZRybw027OR90B90X0OL6eKlaFAM2wowWsu2wqUqfKf9nxQI3kQB/Yw2JOL/9Tlswh4/OqApVInjggsEeI2zxB8Axeo9FKg/3tTuvsCaawdhmWqMGqKUzz1zGu3meTvZlno19dkbpT+/IrXHAbb5QV4W5ecUFC2+6TatBICz4IR/dPjmDzFAvst8AnQ3L4D4uGLaxIOuh4m3ZDEk+h6CHCtl/r3MN+0rAgUT"
    }
  }
}
