{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "synology-csi",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "synology-csi",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "client-info.yaml": "AgCkrl+AgCGa4uA2tolDxvVpBV39SL6B/JI+DTlV8F5MP2pE6nDgPgyimH/qBbKEiUkbWmHlB0dQjjy8lQJvbHNOAnLs6UnWxfk0901tGhb+NYQwcHQRfLE2OPItkXcKK0aoEVQBtqdr+rCXAwJ54QDWoxB0hc6+Nx/Vtuwe/HUj/Kar+/iEak+EPJAxowMuTBYUhB1vv0SnWYnqtpy2XdgE2DAn1+mjs+ubFT4GC8bPVOIOEgQ5CyB0DAxxgMxBnLeAB0tqgeJgFTc/bjQqJScCVuz877AW7JL+CrEigohpWu77G3U9t+8nceGKkRNTtrORP0oB9Nhtt44o/AaG2Tcj0xj2d8E1ioJdlMTlU09lCpxYngJa15hwjlq01x2Jw930N2kQ6CuuDib6I+y8hAcaVmsAhPWlf0xN2SE5yZldUPcip/hn/2maDfwp6ZW6CLG2xarqvcWiSUwnHyj9hC9wT8niXP12hdEcPnQaqDGfLu/cs303UPy4yoIVcCAij5HDaP3lln1i8qU1Zc/g8o5g+pZup3GxUi5GNiiuinmSbvcsOZRonCALN9WGXppOA6QfiOs5t/+C8tFcE6dbKE5e0VHKXFRiRpZFJR/YCZxU0OEweTy1P74yjITUnPo0XeUVpdio/aiD6Vzf7/YofZdtvCGGU5sXkKRrhfEYwl15n8+q5+vuSJEIhpgpmIOssPOPtARZqOjUrUM3AvjWVE2+g7gl5w0yY6lhlBpmb4lCSB1O0U5u+8bp9ZHtHbPBJ5O8gTjH+j3DBog41PjqCyIsaTayWhYOdB6FCqqrZdI9DUCyHGG9CiqDEctHRAm9x7zfcUlMFdE1WMSR5Jzuwt44b/mu/XxDNFDkP9gH1nb3Vfk="
    }
  }
}
